import json

from src.harness.schema import (
    AgentInput,
    AgentOutput,
    PlanningResult,
    ManufacturingProcess,
    QualityCheckpoint,
)
from src.llm.base import LLMProvider
from src.llm.factory import create_llm_provider


class LocalLLMProcessPlanningAgent:
    agent_name = "local_llm_process_planning_agent"

    def __init__(
        self,
        model: str = "qwen2.5:1.5b",
        provider: LLMProvider | None = None,
        provider_name: str | None = None,
    ):
        self.model = model
        self.provider = provider or create_llm_provider(
            provider_name=provider_name,
            ollama_model=self.model,
        )

    def run(self, agent_input: AgentInput) -> AgentOutput:
        try:
            prompt = self._build_prompt(agent_input)
            response_text = self.provider.generate(prompt).text

            result = self._parse_response(response_text, agent_input)

            return AgentOutput(
                task_id=agent_input.task_id,
                agent_name=self.agent_name,
                status="success",
                result=result,
                confidence=0.7,
                errors=[],
                notes=["Generated by Local LLM"],
            )

        except Exception as e:
            return AgentOutput(
                task_id=agent_input.task_id,
                agent_name=self.agent_name,
                status="failure",
                result=None,
                confidence=0.0,
                errors=[str(e)],
                notes=["LLM execution failed"],
            )

    # -------------------------
    # プロンプト（超重要）
    # -------------------------
    def _build_prompt(self, agent_input: AgentInput) -> str:
        return f"""
    あなたは製造工程設計エージェントです。

    # 入力
    file_path: {agent_input.source.file_path}

    # 判定ルール（必ず従う）
    - file_path に以下が含まれる場合は工程を出力する

    【drilling条件】
    - 「穴」「φ」「Φ」「M」「ねじ」「タップ」「ヶ所」
    → process_type="drilling" を出力

    【milling条件】
    - 「フライス」「面加工」「外形」「輪郭」「段付き」「ポケット」
    → process_type="milling" を出力

    【unknown条件】
    - 上記どれにも該当しない場合
    → manufacturing_processes=[]

    # 出力ルール
    - 条件に一致した場合は必ず1件出力する
    - 条件に一致しない場合のみ空配列
    - 推測は禁止

    # checkpoint_type
    - tapping: "thread_gauge_check"
    - reaming: "hole_diameter_precision"
    - surface_grinding: "flatness_check"
    - turning: "outer_diameter_check"
    - drilling → "hole_diameter"
    - milling → "outer_dimension"

    # 出力制約
    - JSONのみ
    - 説明禁止
    - ```禁止

    # 出力形式
    {{
      "manufacturing_processes": [],
      "findings": []
    }}
    """

    # -------------------------
    # JSON → PlanningResult
    # -------------------------
    def _parse_response(self, text: str, agent_input: AgentInput) -> PlanningResult:
        try:
            text = text.strip()

            if "```" in text:
                parts = text.split("```")
                text = parts[1] if len(parts) > 1 else text

            start = text.find("{")
            end = text.rfind("}") + 1

            if start == -1 or end == 0:
                raise ValueError("No JSON object found in LLM response")

            text = text[start:end]
            data = json.loads(text)

            processes = []

            raw_processes = data.get("manufacturing_processes", [])
            if not isinstance(raw_processes, list):
                raw_processes = []

            for index, p in enumerate(raw_processes, start=1):
                if not isinstance(p, dict):
                    continue

                process_type = p.get("process_type", "unknown")

                (
                    default_checkpoint_type,
                    default_process_name,
                    default_target_feature,
                ) = self._process_defaults(process_type)

                raw_checkpoints = p.get("quality_checkpoints", [])
                if not isinstance(raw_checkpoints, list) or not raw_checkpoints:
                    raw_checkpoints = [
                        {
                            "checkpoint_type": default_checkpoint_type,
                            "description": "工程に対応する品質確認を行う",
                            "inspection_method": "measurement",
                            "basis": ["工程に対応する品質確認が必要なため"],
                        }
                    ]

                checkpoints = []
                for qc in raw_checkpoints:
                    if not isinstance(qc, dict):
                        continue

                    checkpoints.append(
                        QualityCheckpoint(
                            checkpoint_type=qc.get(
                                "checkpoint_type", default_checkpoint_type
                            ),
                            description=qc.get("description", "品質確認を行う"),
                            inspection_method=qc.get(
                                "inspection_method", "measurement"
                            ),
                            basis=qc.get("basis", ["品質確認が必要なため"]),
                        )
                    )

                process = ManufacturingProcess(
                    process_id=p.get("process_id", f"P{index:03d}"),
                    process_type=process_type,
                    process_name=p.get("process_name", default_process_name),
                    description=p.get("description", default_process_name),
                    target_feature=p.get("target_feature", default_target_feature),
                    quantity=p.get("quantity", 1),
                    basis=p.get(
                        "basis", [f"LLM output indicated process_type={process_type}"]
                    ),
                    quality_checkpoints=checkpoints,
                    confidence=p.get("confidence", 0.6),
                    needs_review=p.get("needs_review", False),
                )

                processes.append(process)

            raw_findings = data.get("findings", [])
            safe_findings = []
            if isinstance(raw_findings, list):
                for f in raw_findings:
                    if isinstance(f, dict):
                        safe_findings.append(f)

            # Rescue: LLM sometimes puts process_type in findings instead of manufacturing_processes
            if not processes:
                for f in safe_findings:
                    if not isinstance(f, dict):
                        continue

                    rescued_process_type = f.get("process_type") or f.get("condition")

                    if rescued_process_type == "drilling":
                        checkpoint = QualityCheckpoint(
                            checkpoint_type="hole_diameter",
                            description="穴径確認",
                            inspection_method="measurement",
                            basis=["drilling工程では穴径確認が必要なため"],
                        )

                        processes.append(
                            ManufacturingProcess(
                                process_id="P001",
                                process_type="drilling",
                                process_name="穴加工",
                                description="穴加工",
                                target_feature="穴",
                                quantity=4 if "4" in str(f) else 1,
                                basis=["LLM findings indicated process_type=drilling"],
                                quality_checkpoints=[checkpoint],
                                confidence=0.6,
                                needs_review=False,
                            )
                        )

                    elif rescued_process_type == "milling":
                        checkpoint = QualityCheckpoint(
                            checkpoint_type="outer_dimension",
                            description="外形寸法確認",
                            inspection_method="measurement",
                            basis=["milling工程では外形寸法確認が必要なため"],
                        )

                        processes.append(
                            ManufacturingProcess(
                                process_id="P001",
                                process_type="milling",
                                process_name="フライス加工",
                                description="フライス加工",
                                target_feature="外形・面加工部",
                                quantity=1,
                                basis=["LLM findings indicated process_type=milling"],
                                quality_checkpoints=[checkpoint],
                                confidence=0.6,
                                needs_review=False,
                            )
                        )

            fallback_processes = self._fallback_processes_from_input(agent_input)
            existing_process_types = {process.process_type for process in processes}
            for fallback_process in fallback_processes:
                if fallback_process.process_type not in existing_process_types:
                    fallback_process.process_id = f"P{len(processes) + 1:03d}"
                    processes.append(fallback_process)
                    existing_process_types.add(fallback_process.process_type)

            return PlanningResult(
                manufacturing_processes=processes,
                findings=safe_findings,
            )

        except Exception as e:
            fallback_processes = self._fallback_processes_from_input(agent_input)
            if fallback_processes:
                return PlanningResult(
                    manufacturing_processes=fallback_processes,
                    findings=[
                        {
                            "level": "warning",
                            "category": "fallback_after_parse_error",
                            "message": str(e),
                        }
                    ],
                )

            return PlanningResult(
                manufacturing_processes=[],
                findings=[
                    {
                        "level": "error",
                        "category": "parse_error",
                        "message": str(e),
                    }
                ],
            )

    def _fallback_processes_from_input(
        self, agent_input: AgentInput
    ) -> list[ManufacturingProcess]:
        text = "\n".join(
            [
                agent_input.input_type,
                agent_input.source.file_path,
                agent_input.source.file_type,
                agent_input.metadata.part_name,
                agent_input.metadata.drawing_type,
            ]
        )

        detected_process_types = []
        detection_rules = [
            ("tapping", ["タップ", "ねじ加工", "tapping"]),
            ("reaming", ["リーマ", "reaming"]),
            ("surface_grinding", ["平面研削", "研削", "surface_grinding"]),
            ("turning", ["旋削", "turning"]),
            ("milling", ["フライス", "面加工", "輪郭", "段付き", "ポケット", "milling"]),
            ("drilling", ["穴加工", "穴_", "drilling"]),
        ]

        for process_type, keywords in detection_rules:
            if self._contains_any(text, keywords):
                detected_process_types.append(process_type)

        if (
            self._contains_any(text, ["M8", "M10", "M12", "M20"])
            and "tapping" not in detected_process_types
            and "drilling" not in detected_process_types
        ):
            detected_process_types.append("drilling")

        return [
            self._create_fallback_process(process_type, index)
            for index, process_type in enumerate(detected_process_types, start=1)
        ]

    def _fallback_process_from_input(
        self, agent_input: AgentInput
    ) -> ManufacturingProcess | None:
        processes = self._fallback_processes_from_input(agent_input)
        return processes[0] if processes else None

    def _create_fallback_process(
        self, process_type: str, index: int
    ) -> ManufacturingProcess:
        checkpoint_type, process_name, target_feature = self._process_defaults(
            process_type
        )
        checkpoint = QualityCheckpoint(
            checkpoint_type=checkpoint_type,
            description=f"{process_name} quality check",
            inspection_method="measurement",
            basis=[f"Input text indicates {process_type}"],
        )

        return ManufacturingProcess(
            process_id=f"P{index:03d}",
            process_type=process_type,
            process_name=process_name,
            description=f"Input text indicates {process_name}",
            target_feature=target_feature,
            quantity=1,
            basis=[f"Input text indicates process_type={process_type}"],
            quality_checkpoints=[checkpoint],
            confidence=0.6,
            needs_review=True,
        )

    def _process_defaults(self, process_type: str) -> tuple[str, str, str]:
        defaults = {
            "drilling": ("hole_diameter", "穴加工", "穴"),
            "milling": ("outer_dimension", "フライス加工", "外形・面加工部"),
            "tapping": ("thread_gauge_check", "タップ加工", "ねじ部"),
            "reaming": ("hole_diameter_precision", "リーマ加工", "精密穴"),
            "surface_grinding": ("flatness_check", "平面研削", "平面"),
            "turning": ("outer_diameter_check", "旋削", "外径"),
        }
        return defaults.get(
            process_type,
            ("unknown_checkpoint", "unknown", "unknown"),
        )

    def _contains_any(self, text: str, keywords: list[str]) -> bool:
        return any(keyword in text for keyword in keywords)
