from src.harness.schema import (
    AgentInput,
    AgentOutput,
    PlanningResult,
    ManufacturingProcess,
    QualityCheckpoint,
)


class RuleBasedProcessPlanningAgent:
    agent_name = "rule_based_process_planning_agent"

    def run(self, agent_input: AgentInput) -> AgentOutput:
        try:
            source_text = self._collect_source_text(agent_input)

            manufacturing_processes: list[ManufacturingProcess] = []
            findings: list[dict] = []

            if self._has_drilling_feature(source_text):
                manufacturing_processes.append(
                    self._create_drilling_process(source_text)
                )

            if self._has_milling_feature(source_text):
                manufacturing_processes.append(
                    self._create_milling_process()
                )

            if self._has_surface_finish_feature(source_text):
                manufacturing_processes.append(
                    self._create_surface_finish_process()
                )

            if not manufacturing_processes:
                findings.append({
                    "level": "warning",
                    "category": "no_process_detected",
                    "message": "No manufacturing process could be determined by rule-based logic.",
                })

                result = PlanningResult(
                    manufacturing_processes=[],
                    findings=findings,
                )

                return AgentOutput(
                    task_id=agent_input.task_id,
                    agent_name=self.agent_name,
                    status="needs_review",
                    result=result,
                    confidence=0.4,
                    errors=[],
                    notes=[
                        "Rule-based agent returned needs_review because no known process keywords were found."
                    ],
                )

            result = PlanningResult(
                manufacturing_processes=manufacturing_processes,
                findings=findings,
            )

            return AgentOutput(
                task_id=agent_input.task_id,
                agent_name=self.agent_name,
                status="success",
                result=result,
                confidence=0.85,
                errors=[],
                notes=[
                    "PlanningResult was generated by deterministic rule-based logic.",
                    "This agent does not use LLM.",
                ],
            )

        except Exception as e:
            return AgentOutput(
                task_id=agent_input.task_id,
                agent_name=self.agent_name,
                status="failure",
                result=None,
                confidence=0.0,
                errors=[str(e)],
                notes=["Rule-based Process Planning Agent failed during execution."],
            )

    def _collect_source_text(self, agent_input: AgentInput) -> str:
        return "\n".join([
            agent_input.input_type,
            agent_input.source.file_path,
            agent_input.source.file_type,
            agent_input.metadata.part_name,
            agent_input.metadata.drawing_type,
            agent_input.metadata.created_at,
        ])

    def _create_drilling_process(self, text: str) -> ManufacturingProcess:
        checkpoint = QualityCheckpoint(
            checkpoint_type="hole_diameter",
            description="穴径・穴位置・深さを確認する",
            inspection_method="ノギス、ピンゲージ、深さゲージ、三次元測定機",
            basis=["穴加工では径、位置、深さの寸法保証が必要なため"],
        )

        return ManufacturingProcess(
            process_id="P001",
            process_type="drilling",
            process_name="穴加工",
            description="図面または仕様内の穴・ねじ・径指示に基づく穴加工",
            target_feature="穴、ねじ穴、径指定部",
            quantity=self._estimate_quantity(text),
            basis=["入力情報に穴、φ、M、ねじ、タップ、深さ指示のいずれかが含まれるため"],
            quality_checkpoints=[checkpoint],
            confidence=0.85,
            needs_review=False,
        )

    def _create_milling_process(self) -> ManufacturingProcess:
        checkpoint = QualityCheckpoint(
            checkpoint_type="dimensional_inspection",
            description="外形寸法・平面寸法を確認する",
            inspection_method="ノギス、マイクロメータ、三次元測定機",
            basis=["フライス加工では外形寸法および平面精度の確認が必要なため"],
        )

        return ManufacturingProcess(
            process_id="P002",
            process_type="milling",
            process_name="フライス加工",
            description="面加工または外形加工に関する指示に基づくフライス加工",
            target_feature="平面、外形、段付き部、ポケット部",
            quantity=1,
            basis=["入力情報に面加工、フライス、外形、輪郭、切削、段付き、ポケットのいずれかが含まれるため"],
            quality_checkpoints=[checkpoint],
            confidence=0.85,
            needs_review=False,
        )

    def _create_surface_finish_process(self) -> ManufacturingProcess:
        checkpoint = QualityCheckpoint(
            checkpoint_type="surface_inspection",
            description="表面粗さを確認する",
            inspection_method="粗さ測定機、目視確認",
            basis=["表面仕上げ指示があるため、表面性状の確認が必要なため"],
        )

        return ManufacturingProcess(
            process_id="P003",
            process_type="surface_finishing",
            process_name="表面仕上げ",
            description="表面粗さまたは仕上げ記号に基づく表面仕上げ",
            target_feature="表面粗さ指定部",
            quantity=1,
            basis=["入力情報にRa、表面粗さ、▽、仕上げのいずれかが含まれるため"],
            quality_checkpoints=[checkpoint],
            confidence=0.8,
            needs_review=False,
        )

    def _has_drilling_feature(self, text: str) -> bool:
        keywords = ["穴", "φ", "Φ", "M8", "M10", "M12", "M20", "ねじ", "タップ", "深"]
        return any(keyword in text for keyword in keywords)

    def _has_milling_feature(self, text: str) -> bool:
        keywords = ["面加工", "フライス", "外形", "輪郭", "切削", "段付き", "ポケット"]
        return any(keyword in text for keyword in keywords)

    def _has_surface_finish_feature(self, text: str) -> bool:
        keywords = ["Ra", "RA", "表面粗さ", "▽", "仕上げ"]
        return any(keyword in text for keyword in keywords)

    def _estimate_quantity(self, text: str) -> int:
        if "4×" in text or "4ヶ所" in text or "4か所" in text:
            return 4
        if "2×" in text or "2ヶ所" in text or "2か所" in text:
            return 2
        return 1